#'name in documen' : 'new name' for etl in etl.py
dict_etl = {'Id:':'Id',
            'Patient nbr:':'patient_nbr',
            'First Name:':'FirstName',
            'Last Name:':'LastName',
            'Payer Code:':'payer_code',
            'Race:':'race',
            'Gender:':'gender',
            'Age:':'age',
            'Diag 1:':'diag_1',
            'Diag 2:':'diag_2',
            'Diag 3:':'diag_3',
            'Admission Source ID:':'admission_source_id',
            'Admission Type ID:':'admission_type_id',
            'Discharge Disposition Id:':'admission_source_id',
            'Number Diagnoses:':"number_diagnoses",
            'Number Diagnoses:':"number_diagnoses",
            'Number inpatient:': "number_inpatient",
            'Num Lab Procedures:': "num_lab_procedures",
            'Num Medications:': "num_medications",
            'Number Outpatient:': "number_outpatient",
            'Time in hospital:': "time_in_hospital",
            'Number emergency:': "number_emergency",
            'Num procedures:': "num_procedures",
            'Change:': "change",
            'Diabetes Medication:': "diabetesMed",
            'Max glu serum:': "max_glu_serum",
            'A1C Result:': "A1Cresult"
            }
